In [2]:
import numpy as np
import math
import matplotlib.pyplot as plt

In [19]:
import random
random.choice(sa)

1

In [20]:
si=random.choice(sa)
sj=random.choice(sa)

In [24]:
def probability(p):
    count(si*sj >0) / (n*(n-1)

SyntaxError: unexpected EOF while parsing (<ipython-input-24-a50eec356848>, line 2)

In [35]:
A = [1]*10

In [36]:
A

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [37]:
A = [1]* 10, [2]*10

In [38]:
A

([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [39]:
A = [1*10, 2*10]

In [40]:
A

[10, 20]

In [41]:
A = 1*10, 2*10

In [42]:
A

(10, 20)

In [43]:
A = ([1*10, 2*10])

In [44]:
A

[10, 20]

In [45]:
A = [1]* 10, [2]*10

In [46]:
si=random.choice(A)

In [47]:
si

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [48]:
si

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [49]:
A

([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [51]:
A=[1, 2]

In [52]:
A

[1, 2]

In [53]:
A*10

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [54]:
A=A*10

In [55]:
A

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [56]:
B=[-1]*20

In [57]:
B

[-1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1]

In [58]:
si=random.choice(A)

In [59]:
si

2

In [60]:
si

2

In [61]:
si

2

In [62]:
si

2

In [63]:
si

2

In [64]:
si

2

In [65]:
si

2

In [67]:
si=1

In [68]:
si

1

In [69]:
si=random.choice(A)

In [70]:
si

1

In [71]:
si

1

In [72]:
si

1

In [73]:
si

1

In [74]:
random.choice(A) = si

SyntaxError: can't assign to function call (<ipython-input-74-fc5d58319501>, line 1)

In [75]:
si = random.choice(A)

In [76]:
si

2

In [77]:
si*si

4

In [ ]:
A=np.array

NameError: name 'xrange' is not defined

0.9581268498728304
0.5924937818156412
0.9727852065387657
0.9656884998590258
0.9531415200067498
0.6711965166354834
0.4944816989676457
0.9658098520713958
0.09642754003241671
0.10066132005594186


In [177]:
A[i : j] = np.random.random((10,10))

NameError: name 'j' is not defined

In [87]:
si

array([[0.91852096, 0.30057328, 0.92084366, 0.30216274, 0.79671958,
        0.78247364, 0.52100714, 0.73896878, 0.70005102, 0.26747576],
       [0.30854054, 0.88547321, 0.9581637 , 0.59599681, 0.92408352,
        0.82944486, 0.48484574, 0.55299867, 0.92861049, 0.01578185],
       [0.33554461, 0.54296563, 0.99795139, 0.7610028 , 0.93717049,
        0.34355481, 0.99347658, 0.41432723, 0.63298054, 0.51473711],
       [0.86013082, 0.0839738 , 0.53724279, 0.56925697, 0.8151353 ,
        0.71361114, 0.87993036, 0.72468473, 0.76094447, 0.34938588],
       [0.64147975, 0.58945773, 0.30915551, 0.55139511, 0.48362433,
        0.72596356, 0.68751732, 0.88543027, 0.81216206, 0.22397012],
       [0.68122356, 0.0706831 , 0.88867431, 0.23954262, 0.61712822,
        0.10292685, 0.23398776, 0.38166307, 0.91468465, 0.91239791],
       [0.05677406, 0.48759357, 0.1846511 , 0.53146452, 0.25589173,
        0.69501834, 0.3415811 , 0.03105812, 0.83309766, 0.6943543 ],
       [0.43398353, 0.16216584, 0.6396677

In [118]:
A = si*2

In [119]:
A

array([[1.83704193, 0.60114655, 1.84168732, 0.60432549, 1.59343916,
        1.56494729, 1.04201428, 1.47793755, 1.40010204, 0.53495153],
       [0.61708107, 1.77094642, 1.9163274 , 1.19199363, 1.84816703,
        1.65888971, 0.96969148, 1.10599733, 1.85722099, 0.0315637 ],
       [0.67108922, 1.08593126, 1.99590278, 1.52200561, 1.87434098,
        0.68710962, 1.98695316, 0.82865446, 1.26596109, 1.02947422],
       [1.72026164, 0.16794761, 1.07448557, 1.13851395, 1.6302706 ,
        1.42722228, 1.75986072, 1.44936946, 1.52188895, 0.69877176],
       [1.28295951, 1.17891546, 0.61831102, 1.10279022, 0.96724865,
        1.45192711, 1.37503464, 1.77086053, 1.62432412, 0.44794025],
       [1.36244713, 0.1413662 , 1.77734861, 0.47908524, 1.23425643,
        0.20585369, 0.46797553, 0.76332614, 1.82936929, 1.82479582],
       [0.11354811, 0.97518714, 0.3693022 , 1.06292904, 0.51178346,
        1.39003669, 0.6831622 , 0.06211624, 1.66619531, 1.3887086 ],
       [0.86796706, 0.32433168, 1.2793355

In [160]:
if np.array(A) > 1 :
    np.array(A) = 2

SyntaxError: can't assign to function call (<ipython-input-160-55db07888969>, line 2)

In [165]:
if A[i, j] >=1 :
    A[i, j] = 2
if A[i, j] <1 :
    A[i, j] = 1

NameError: name 'j' is not defined

In [166]:
i

array([1.83704193, 0.60114655, 1.84168732, 0.60432549, 1.59343916,
       1.56494729, 1.04201428, 1.47793755, 1.40010204, 0.53495153])

In [167]:
j

NameError: name 'j' is not defined

In [161]:
A(1,1)

TypeError: 'numpy.ndarray' object is not callable

In [163]:
A[1, 1]

1.7709464154175392

In [164]:
A[1, 1]

1.7709464154175392

In [169]:
A

array([[1.83704193, 0.60114655, 1.84168732, 0.60432549, 1.59343916,
        1.56494729, 1.04201428, 1.47793755, 1.40010204, 0.53495153],
       [0.61708107, 1.77094642, 1.9163274 , 1.19199363, 1.84816703,
        1.65888971, 0.96969148, 1.10599733, 1.85722099, 0.0315637 ],
       [0.67108922, 1.08593126, 1.99590278, 1.52200561, 1.87434098,
        0.68710962, 1.98695316, 0.82865446, 1.26596109, 1.02947422],
       [1.72026164, 0.16794761, 1.07448557, 1.13851395, 1.6302706 ,
        1.42722228, 1.75986072, 1.44936946, 1.52188895, 0.69877176],
       [1.28295951, 1.17891546, 0.61831102, 1.10279022, 0.96724865,
        1.45192711, 1.37503464, 1.77086053, 1.62432412, 0.44794025],
       [1.36244713, 0.1413662 , 1.77734861, 0.47908524, 1.23425643,
        0.20585369, 0.46797553, 0.76332614, 1.82936929, 1.82479582],
       [0.11354811, 0.97518714, 0.3693022 , 1.06292904, 0.51178346,
        1.39003669, 0.6831622 , 0.06211624, 1.66619531, 1.3887086 ],
       [0.86796706, 0.32433168, 1.2793355

In [170]:
i

array([1.83704193, 0.60114655, 1.84168732, 0.60432549, 1.59343916,
       1.56494729, 1.04201428, 1.47793755, 1.40010204, 0.53495153])

In [174]:
 = si*2

SyntaxError: invalid syntax (<ipython-input-174-d882d32f3dc4>, line 1)

In [130]:
for 
if any(A) >=1 :
    "True" == 2
elif any(A) < 1 :
    "False" == 1

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [3]:
D = np.linspace(0, 5, 100)


In [4]:
D

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [ ]:
j

In [ ]:
p>=0, q>=0
p + q = 1
r = p / q